language: node_js

stages:
  - basic

matrix:
  include:
    - os: linux
      node_js: "12"
      env: JOB_PART=test
      stage: basic
    - os: linux
      node_js: "10"
      env: JOB_PART=test
      stage: basic
    - os: linux
      node_js: "8"
      env: JOB_PART=test
      stage: basic
    - os: linux
      node_js: "6"
      env: JOB_PART=test
      stage: basic
  fast_finish: true

sudo: false
script: yarn run $JOB_PART
after_script: yarn run coverage
