language: node_js

node_js:
  - "8"
  - "10"
  - "12"

cache:
  yarn: true

matrix:
  fast_finish: true

stages:
  - test
  - release

if: tag IS blank

jobs:
  include:
    - stage: test
      sudo: false
      script:
        - yarn run test
      after_script:
        - yarn run coverage
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: "12"
      # Advanced: overwrite your default `script` step to skip the tests
      script: skip
      before_deploy:
        - yarn run build
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn run semantic-release
        on:
          repo: niieani/hashids.js
          all_branches: true
